name: CI

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    name: Ruff Check
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Ruff Check
        run: |
          apk update && apk upgrade --no-cache
          apk add ruff --no-cache
          ruff check kpa

  shellcheck-lint:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    name: ShellCheck Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: ShellCheck Lint
        run: |
          apk update && apk upgrade --no-cache
          apk add shellcheck --no-cache
          shellcheck mkpa.sh --format=diff --enable=all --shell=sh
