name: CI

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v5
      - name: flake8 Lint
        run: |
          apk update && apk upgrade --no-cache
          apk add py3-flake8 --no-cache
          flake8 kpa